version: "3.3"

services:
  db:
    image: postgres
    container_name: pay_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments
    volumes:
      - .:/code
    command: ./docker_commands.sh
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pg_data:
